import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Removed the `Content` import
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import SearchModal from "./components/modals/SearchModal";
import Modal from "./components/modals/Modals";
import AddPropertyModal from "./components/modals/AddPropertyModal";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VacyStay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const modalContent = <p>Yadsa</p>; // Renamed variable to avoid conflict

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body className={inter.className}>
        <Navbar />
        <div className="pt-24">{children}</div>

        {/* Modals */}
        {/* Uncomment the Modal component if you need to display it */}
        {/* <Modal label="Title" content={modalContent} isOpen={true} /> */}
        <LoginModal />
        <SearchModal />
        <SignupModal />
        <AddPropertyModal />
      </body>
    </html>
  );
}
